apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "django-app.serviceAccountName" . }}
            namespace: {{ .Release.Namespace }}
