{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: django-app-secret
  labels:
    app.kubernetes.io/name: django-app
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.externalSecrets.secretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.externalSecrets.postgresPassword | quote }}
{{- end }}
