apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "django-app.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: django-app
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

